# Generated by Django 5.2 on 2025-04-25 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_remove_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='complaint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='complaint.complaint'),
        ),
    ]
